spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;
    username: test
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

    
server:
  port: 8080
  address: localhost
  servlet:
    context-path: /prices